# Generated by Django 3.2.9 on 2021-12-29 08:54

from django.db import migrations, models
import mainAdmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120, null=True)),
                ('order_id', models.TextField(max_length=120, null=True)),
                ('user', models.TextField(max_length=120, null=True)),
                ('price', models.TextField(max_length=200, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('quantity', models.TextField(default=1, max_length=100, null=True)),
                ('image', models.TextField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('price', models.TextField(max_length=150)),
                ('quantity', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mainAdmin.models.filepath)),
            ],
        ),
    ]
