# Generated by Django 3.2.9 on 2021-12-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAdmin', '0002_auto_20211229_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userName',
            new_name='image',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.TextField(default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
