# Generated by Django 3.2.9 on 2021-12-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAdmin', '0003_auto_20211229_1015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orderItems',
        ),
    ]
