# Generated by Django 3.2.9 on 2022-01-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAdmin', '0005_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=120, null=True)),
                ('lastName', models.TextField(max_length=120, null=True)),
                ('userName', models.TextField(max_length=120, null=True)),
                ('city', models.TextField(max_length=120, null=True)),
                ('zip', models.IntegerField(max_length=50, null=True)),
                ('paymentMethod', models.TextField(max_length=200, null=True)),
                ('total', models.IntegerField(max_length=100, null=True)),
                ('checkoutId', models.TextField(max_length=130, null=True)),
            ],
        ),
    ]
