# Generated by Django 3.2.9 on 2022-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAdmin', '0006_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='state',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
