# Generated by Django 3.2.9 on 2022-01-03 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAdmin', '0007_checkout_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='total',
            new_name='totalCheck',
        ),
    ]
