# Generated by Django 3.2.9 on 2022-01-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAdmin', '0008_rename_total_checkout_totalcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='totalCheck',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
